name: build
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 5 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '22'
      - uses: wtfjoke/setup-groovy@v2
        with:
          groovy-version: '4.0.21'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.8
      - run: java -version
      - run: groovy --version
      - run: gradle -version
      - run: gradle clean build
